# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
d1 = np.array([10,30,40])

# Create a 2-dimensional NumPy array using np.array()
d2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
d3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[4,5,6],[95,6,7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
d1.shape, d1.ndim, d1.dtype, d1.size, type(d1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
d2.shape, d2.ndim, d2.dtype, d2.size, type(d2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
d3.shape, d3.ndim, d3.dtype, d3.size, type(d3)

((3, 2, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(d2)
df

,0,1,2
0,1,2,3
1,4,5,6


In [8]:
# Create an array of shape (10, 2) with only ones
one = np.ones((2,3),int)
one

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros((2,3),int)
zero

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
rarrange = np.arange(0,100,3)
rarrange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random = np.random.randint(0,10,size=(7,2))
random

array([[7, 6],
       [9, 5],
       [4, 5],
       [0, 8],
       [3, 5],
       [9, 8],
       [0, 0]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random2 = np.random.rand(3,5)
random2

array([[0.59718807, 0.61576883, 0.6640802 , 0.91809173, 0.5480771 ],
       [0.78927464, 0.23976671, 0.80601763, 0.48568372, 0.25288099],
       [0.53824103, 0.43897205, 0.31564415, 0.34648925, 0.52495188]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
numbers = np.random.randint(0,10,size=(4,6))
numbers

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [21]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([1, 2, 3, 4, 5, 7, 9])

In [24]:
# Find the 0'th index of the latest array you created
random_array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [26]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[9, 1],
       [5, 3]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random1 = np.random.randint(0,10,size=(3,5))
one1 = np.ones((3,5),int)

In [31]:
# Add the two arrays together
random1 + one1

array([[10,  2, 10,  4,  8],
       [ 7,  9,  8,  5,  2],
       [ 5,  8, 10,  9,  9]])

In [33]:
# Create another array of ones of shape (5, 3)
one2 = np.ones((5,3),int)

In [36]:
# Try add the array of ones and the other most recent array together
one1 + one2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is? Dimensions

How would you fix it? reshape or transpose

In [37]:
# Create another array of ones of shape (3, 5)
one3 = np.ones((3,5),int)

In [39]:
# Subtract the new array of ones from the other most recent array
one2 - one3

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [40]:
# Multiply the ones array with the latest array
one1 * one3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
# Take the latest array to the power of 2 using '**'
random1 ** 2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [43]:
# Do the same thing with np.square()
np.square(random1)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [44]:
# Find the mean of the latest array using np.mean()
np.mean(random1)

np.float64(6.066666666666666)

In [45]:
# Find the maximum of the latest array using np.max()
np.max(random1)

np.int64(9)

In [46]:
# Find the minimum of the latest array using np.min()
np.min(random1)

np.int64(1)

In [47]:
# Find the standard deviation of the latest array
np.std(random1)

np.float64(2.6948510575210314)

In [48]:
# Find the variance of the latest array
np.var(random1)

np.float64(7.262222222222222)

In [49]:
# Reshape the latest array to (3, 5, 1)
random1.reshape(3,5,1)

array([[[9],
        [1],
        [9],
        [3],
        [7]],

       [[6],
        [8],
        [7],
        [4],
        [1]],

       [[4],
        [7],
        [9],
        [8],
        [8]]])

In [50]:
# Transpose the latest array
random1.T

array([[9, 6, 4],
       [1, 8, 7],
       [9, 7, 9],
       [3, 4, 8],
       [7, 1, 8]])

What does the transpose do? Swap dimensions

In [52]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0,10,size=(3,3))
array2 = np.random.randint(0,10,size=(3,2))

In [53]:
# Perform a dot product on the two newest arrays you created
array1.dot(array2)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3 = np.random.randint(0,10,size=(4,3))
array4 = np.random.randint(0,10,size=(4,3))

In [55]:
# Perform a dot product on the two newest arrays you created
np.dot(array3,array4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it? reshape or transpose

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(array3,array4.T)

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array5 = np.random.randint(0,10,size=(3,3))
array6 = np.random.randint(0,10,size=(3,3))

In [59]:
# Compare the two arrays with '>'
array5 > array6

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [60]:
# Compare the two arrays with '>='
array5 >= array6

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [61]:
# Find which elements of the first array are greater than 7
array5 > 7

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [62]:
# Which parts of each array are equal? (try using '==')
array5 == array6

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [63]:
# Sort one of the arrays you just created in ascending order
np.sort(array5)

array([[6, 6, 8],
       [2, 9, 9],
       [0, 3, 6]])

In [64]:
# Sort the indexes of one of the arrays you just created
np.argsort(array5)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 2, 0]])

In [65]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array5)

np.int64(3)

In [66]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array5)

np.int64(7)

In [67]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array5,axis=1)

array([2, 0, 0])

In [68]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array5)

np.int64(7)

In [71]:
# Create an array of normally distributed random numbers
array7 = np.random.randn(3,5)
array7

array([[-1.24944372, -0.44176602, -0.08416509,  1.23701607, -1.42647888],
       [ 0.33802266,  1.9745712 ,  1.96503476, -1.93991122, -0.76262696],
       [ 0.16865939, -1.32187695, -0.6682467 , -0.137291  ,  1.40132156]])

In [72]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array8 = np.linspace(1,100,10)
array8

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.